In [42]:
import pandas as pd

In [43]:
df = pd.read_csv("scripts_all.csv")

In [45]:
df.tail()

              movie                                           dialogue
0          Avengers  [{'name': 'FURY', 'text': 'How bad is it?'}, {...
1  Avengers_Endgame  [{'name': 'TONY', 'text': '(offering his hand)...
2          IRON MAN  [{'name': 'TONY', 'text': 'Oh, I get it.  You ...
3              THOR  [{'name': 'THOR', 'text': "Written by Ashley M...
4     THOR RAGNAROK  [{'name': 'THOR', 'text': "Now I know what you...

In [46]:
df.shape

(5, 2)

In [47]:
df.iloc[-1]["dialogue"]

'[{\'name\': \'THOR\', \'text\': "Now I know what youâ€™re thinking. Oh no!  Thorâ€™s in a cage.  How did this happen? (then:) Well, sometimes you have to get captured just to get a straight answer out of somebody. Itâ€™s a long story but basically I\'m a bit of a hero. See, I spent some time on earth, fought some robots, saved the planet a couple of times. Then I went searching through the cosmos for some magic, colorful Infinity Stone things... didnâ€™t find any. Thatâ€™s when I came across a path of death and destruction which led me all the way here into this cage... where I met you. Reveal that heâ€™s talking to a weird alien skeleton in chains. THOR (CONTâ€™D) How much longer do you think weâ€™ll be here? NOISE.  Sounds of metal gears TURNING. Suddenly the bottom DROPS OUT!  Thor PLUMMETS until - SHLINK! Chains CINCH and abruptly halt his descent.  Thor dangles six feet off the ground.  Pull back to reveal we are in- INT. SURTURâ€™S LAIR - CONTINUOUS 3 3 A cavernous space.  The walls, floors, and ceilings are molten rock, which has creepy glimmers of fire within it. Stationed in the center is a volcanic rock throne, and sitting in that throne is a charred demonic skeleton. SURTUR (O.S.) Thor, Son of Odin. Thorâ€™s chain turns to reveal- -SURTUR on his throne.  Eighteen-feet-tall, flesh made of fire, and demonic spiked horns on his skull."}, {\'name\': \'THOR\', \'text\': \'Surtur.  Son of a bitch...youâ€™re still alive!  I thought my father killed you, like, half a million years ago. SURTUR I cannot die. Not until I fulfill my destiny and lay waste to your home.\'}, {\'name\': \'THOR\', \'text\': \'You know, itâ€™s funny you should mention that because Iâ€™ve been having these terrible dreams of late.  Asgard up in flames, falling to ruins, and you Surtur are at the center of all of them. SURTUR Then you have seen Ragnarok, the fall of Asgard. The great prophecy-- THOR (O.S.) Hang on.  Hang on. Reveal that Thorâ€™s chain is turning VERY SLOWLY. THOR (CONTâ€™D) Iâ€™ll be back around shortly.  I really feel like we were connecting there. After a beat, Thor rotates around to face Surtur. THOR (CONTâ€™D) Okay, so, Ragnarok. Tell me about that. Walk me through it. BLUE DRAFT 05/20/16 2. SURTUR My time has come. When my crown is reunited with the Eternal Flame, I shall be restored to my full might. I will tower over the mountains and bury my sword deep in Asgardâ€™s--\'}, {\'name\': \'THOR\', \'text\': \'Oh, hang on.  Give it a second. Once again, Thor is turning VERY SLOWLY. THOR (CONTâ€™D) I swear Iâ€™m not even moving, itâ€™s just doing this on its own.  Iâ€™m really sorry. (then:) Okay, let me get this straight. Youâ€™re going to put your crown into the Eternal Flame, and then youâ€™ll suddenly grow as big as a house-- SURTUR A mountain!\'}, {\'name\': \'THOR\', \'text\': \'The Eternal Flame that Odin keeps locked away on Asgard? Surtur grins, evil. SURTUR Odin is not on Asgard. And your absence has left the throne defenseless. That elicits a concerned look from Thor.\'}, {\'name\': \'THOR\', \'text\': \'Okay, so where is it? This crown? SURTUR This is my Crown, the source of my power. Surtur points at the V-shaped horns on his head..\'}, {\'name\': \'THOR\', \'text\': \'Oh, thatâ€™s a crown? I thought it was a big eyebrow. SURTUR Itâ€™s a crown. BLUE DRAFT 05/20/16 3.\'}, {\'name\': \'THOR\', \'text\': \'Anyway, it sounds like all I have to do to stop Ragnarok is rip that thing off your head. Surtur stands up and approaches Thor, DRAGGING his sword. SURTUR But Ragnarok has already begun. You cannot stop it.  I am Asgardâ€™s doom, and so are you.  All will suffer, all will burn. Surtur steps forward and GRABS the chain above Thorâ€™s feet, holding it so he and Thor are face to face.\'}, {\'name\': \'THOR\', \'text\': \'Thatâ€™s intense.  To be honest, seeing you grow really big and set fire to a planet would be quite the spectacle.  But it looks like Iâ€™m going to have to go with option B where I bust out of these chains, knock that tiara off your head, and stash it away in Asgardâ€™s vault. SURTUR You cannot stop Ragnarok. Why fight it? Behind his back, Thor opens his hand.  Sending out the SOS.\'}, {\'name\': \'THOR\', \'text\': \'Because thatâ€™s what heroes do. Nothing happens.  Thor appears annoyed at himself. THOR (CONTâ€™D) Wait, sorry.  I didnâ€™t time that right. (pause) And, now! BOOM!  Thorâ€™s hammer Mjolnir CRASHES through the wall! Thor BREAKS FREE from his chains, GRABS Mjolnir, spins, and flies a distance away. He FLINGS Mjolnir back at Surtur, smashing the giant in the face. Mjolnir returns. SURTUR You have made a grave mistake, Odinson. BLUE DRAFT 05/20/16 4. THE WALLS COME ALIVE!  A seemingly infinite swarm of FIRE DEMONS rally to Surturâ€™s aid.\'}, {\'name\': \'THOR\', \'text\': \'I make grave mistakes all the time. Everything seems to work out. In the shadows, a massive FIRE DRAGON ROARS. The fire demons SURGE FORWARD.  Thor backs up, HAMMERING AWAY.  He then leaps back, SPRINGBOARDS off the wall, and- -LANDS HARD, SLAMMING Mjolnir down.  The resulting shockwave KNOCKS BACK THE LEGION OF FIRE DEMONS. The Fire Dragon STRAINS against a chain leash. Thor is now facing off with Surtur.  Surtur thrusts his hands at Thor, generating a humongous PROJECTILE WALL OF FIRE! Thor SPINS Mjolnir so fast that it creates a kind of SHIELD. The God of Thunder and the Fire Giant engage in ferocious hand-to-hand combat.  Each landing power shots, sending sparks of both fire and electricity into the air. Thor SLIPS behind Surtur and TAKES OUT his knees.  Thor then LAUNCHES HIGH into the air and summons a HUGE LIGHTNING BOLT. Descending hard, he uses all his power to- -LOP SURTURâ€™S HEAD OFF OF HIS BODY!  Surturâ€™s body DEFLATES and COLLAPSES into a heap of charred bones. Thor straps the crowned skull to his back. He turns to find- -the army of Fire Demons regrouping as reinforcements flood in, filling the space to capacity.  Recognizing the threat, Thor thrusts Mjolnir above his head. THOR (CONTâ€™D) Heimdall. I know itâ€™s been a while, but I could use a fast exit! Nothing.  Thor just stands there as the Fire Demons advance. THOR (CONTâ€™D) ...Heimdall? INT. THE OBSERVATORY - SAME 4 4 Heimdall is nowhere to be found.  Instead, we meet SKURGE. Heâ€™s bald, strong, mean looking, a little eager to be liked. BLUE DRAFT 05/20/16 5. At the moment, Skurge is entertaining two ASGARDIAN WOMEN. SKURGE Heimdall was an idiot.  This job should have made him rich.  Now, the job ainâ€™t easy, but it does have its benefits. The Bi-Frost gives me access to everything the Nine Realms have to offer. I mean itâ€™s all mine for the taking. (beat) Behold...my stuff. Skurge has drawn their attention to a pile of weapons and treasures he has stashed off to the side. He hefts up two M-16 assault rifles, trying to play it cool. SKURGE (CONTâ€™D) Iâ€™m particularly fond of these. I pulled â€˜em out of a place on Midgard called Texas.  I even named them. Des and Troy.  You see, when you put them together...they destroy. INT. SURTURâ€™S LAIR - CONTINUOUS 5 5 Having expected to have been Bi-Frosted out of there, Thor is OVERRUN BY THE GIANT WAVE OF FIRE DEMONS! The Fire Dragon BREAKS FREE of its chain. Realizing heâ€™s in trouble, Thor TAKES OFF, rocketing up to- EXT. MUSPELHEIM - CONTINUOUS 6 6 Thor CRASHES out of the ground and LANDS on a craggy surface. Disoriented and singed from the fire demon onslaught. Thorâ€™s cloak is on fire, and he frantically PATS OUT the flames. He picks up Mjolnir, holds it up once more. Nothing.\'}, {\'name\': \'THOR\', \'text\': \'Heimdall, come on. THE GROUND SHAKES!  Like an earthquake.  Thor backs up as the ground begins to give way all around him.  And then- -THE FEARSOME FIRE DRAGON BURSTS OUT OF THE GROUND!  The dragon opens its tremendous jaws for an ear-splitting roar... BLUE DRAFT 05/20/16 6. ...but Thor STUFFS Mjolnir into its mouth and lets go. THUD!  The hammer DROPS, pinning the beast down by its bottom jaw.  It THRASHES and GROWLS, trying to break free. THOR (CONTâ€™D) Stay. (looks up to the sky:) Iâ€™m running short on-- Thor notices that all around him the ground is CRUMBLING like a field of sinkholes giving way to more snarling Fire Demons! THOR (CONTâ€™D) -options. Thor calls for Mjolnir and TAKES OFF.  The dragon SCREECHES! OMITTED 7 7 OMITTED 8 8 INT. THE OBSERVATORY - SAME 9 9 Skurge continues showing off for the ladies. THOR (O.S.) Heimdall? Behind Skurge the Bi-Frost starts MOVING.  One of the women notices the Bi-Frost glowing. ASGARDIAN WOMAN Skurge, is that important? Skurge turns and notices the Bi-Frost activity. SKURGE You girls are in for a treat. Angle on Heimdallâ€™s sword, which has been sloppily cast aside in another pile of â€œstuff.â€\\x9d Skurge hastily runs and grabs it. EXT. MUSPELHEIM - CONTINUOUS 10 10 Thor is FLYING at top speed, but that dragon is right on his heels! The fire demons LAUNCH flaming projectiles from below! Thor looks back, genuinely nervous.  The dragon is OPENING its jaws to swallow Thor whole when- -Suddenly Bi-Frost OPENS!  The portal surrounds Thor and engulfs the dragonâ€™s head!  In an instant, theyâ€™re gone. BLUE DRAFT 05/20/16 7. MAIN TITLE INT. THE OBSERVATORY - MOMENTS LATER 11 11 Skurge has plunged Heimdallâ€™s sword into Bi-Frost. BOOM! Thor EXPLODES out of the portal along with the severed head of the dragon!  SPLAT!  Blood and guts RAIN DOWN on Skurge and the two women, DRENCHING them with purple gore. The dragonâ€™s head SLIDES slowly across the floor, coming to rest right in front of the women who are frozen in shock. The women SHRIEK and rush out of the Observatory.  Thor meanwhile is clean and staggering back to his feet. He looks up to Skurge, who is wiping dragon guts off of himself. SKURGE Girls! (beat) Well well, look who decided to pop in.  Thanks for scaring away my company and drenching my workplace in brains.\'}, {\'name\': \'THOR\', \'text\': \'Who are you? SKURGE Donâ€™t you remember?  Iâ€™m Skurge. (Thor doesnâ€™t) We fought together on Vanaheim.\'}, {\'name\': \'THOR\', \'text\': \'Right.  Whereâ€™s Heimdall? SKURGE That traitor.  No one knows, heâ€™s a fugitive of the throne.\'}, {\'name\': \'THOR\', \'text\': \'Traitor? SKURGE Yeah, you see, Odin charged Heimdall with negligence of duty, but he disappeared before the trial.  Hard to catch a guy who can see everything in the Universe. Thor starts to say something, but then gives up. Instead he starts towards the exit... but Skurge stands in his way. BLUE DRAFT 05/20/16 8.\'}, {\'name\': \'THOR\', \'text\': \'Sure. SKURGE Hold on.  Iâ€™m supposed to announce your arrival. Thor SPINS UP Mjolnir and takes off in a blur.  Skurge starts the loooong run down the Rainbow Bridge. OMITTED 12 12 EXT. THEATER ENTRANCE - DAY A13 A13 THOR arrives with Surturâ€™s skull. Thereâ€™s a small crowd making its way through a threshold over which stands a monumental statue of Loki, arms out-stretched in the â€˜saviorâ€™ pose. Confused, Thor turns to a theater patron.\'}, {\'name\': \'THOR\', \'text\': \'What the hell is that? EXT. ASGARD - ROYAL TERRACE - PATIO - MOMENTS LATER 13 13 LOKI falls into frame, GASPING FOR BREATH... although itâ€™s not Loki. This is ACTOR LOKI and weâ€™re watching a STAGE PLAY. In the background, a single musician plays the haunting score from THOR: THE DARK WORLD on a pan flute. Suddenly, ACTOR THOR leans into shot, holding Actor Loki. ACTOR LOKI Oh, brother.  This is it.  I take my leave. ACTOR THOR You fool, you didnâ€™t listen! ACTOR LOKI Iâ€™m sorry. ACTOR THOR Lady Sif!  Get help! â€œSifâ€\\x9d awkwardly runs off. The â€œWarriors Threeâ€\\x9d watch sadly. A small choir JOINS IN as the music builds to a CRESCENDO. ACTOR SIF Somebody help! BLUE DRAFT 05/20/16 9. In the middle of the audience we reveal ODIN, sitting upon a chaise lounge, sipping wine and thoroughly enjoying the show. Unseen, Thor arrives behind the audience and watches. ACTOR LOKI Sorry for all Iâ€™ve done. ACTOR THOR Itâ€™s all right.   Hold on. ACTOR LOKI Iâ€™m sorry I tried to rule Earth. ACTOR THOR Theyâ€™d be lucky to have you. ACTOR LOKI Iâ€™m sorry about that thing with the Tesseract.  I just couldnâ€™t help myself. ACTOR THOR I know. ACTOR LOKI Iâ€™m a trickster. ACTOR THOR So mischievous. ACTOR LOKI Sorry about that time I turned you into a frog. ACTOR THOR It was a wonderful joke. ODIN (to no-one in particular) Twas indeed hilarious. ACTOR THOR You are the savior of Asgard. ACTOR LOKI Tell my story. ACTOR THOR I will. ACTOR LOKI Build a statue for me. BLUE DRAFT 05/20/16 10. ACTOR THOR We will build a big statue for you. ACTOR LOKI With my helmet on, with the big bendy horns. ACTOR THOR I will tell Father what you did here today. Odin mouths Actor Lokiâ€™s final line along with him. ACTOR LOKI I didnâ€™t do it for him. Actor Loki then â€œdiesâ€\\x9d. ACTOR THOR Noooooo!!! The brothers freeze in a TABLEAU as ACTOR ODIN steps forward. ACTOR ODIN And so Loki died of his wounds, giving his life for ours.  He fought back those disgusting dark elves.  He brought peace to the realm. He takes a 4-YEAR-OLD BOY, PAINTED BLUE, into his arms. ACTOR ODIN (CONTâ€™D) Loki, my boy...â€˜Twas many moons ago I found you on a frost-bitten battlefield. Thor watches, incredulous.  He then notices that a woman next to him is openly SOBBING at the play. ACTOR ODIN (CONTâ€™D) On that day, I did not yet see in you Asgardâ€™s savior.  No.  You were merely a little blue baby icicle... that melted this old foolâ€™s heart. The crowd erupts in rapturous applause. The players bow. Odin stands up, leading the crowd in this STANDING OVATION. ODIN Bravo!  Bravo!  Well done.  Bravo.\'}, {\'name\': \'THOR\', \'text\': \'Father. BLUE DRAFT 05/20/16 11. Odin sees Thor taking a knee.  Curses under his breath: ODIN Oh, shit. (then, announcing) My son!  Thor has returned! Greetings my boy. Odin goes through a weird internal transformation. His fluidity is replaced by a rigid and regal posture. He bats away his maiden and turns to Thor, who stands up.\'}, {\'name\': \'THOR\', \'text\': \'Itâ€™s an interesting play.  Whatâ€™s it called? ODIN The Tragedy of Loki of Asgard. The people wanted to commemorate him.\'}, {\'name\': \'THOR\', \'text\': \'Indeed they should. (provoking) I like that statue.  A lot better looking than he was when he was alive, though.  A little less weasely.  Less greasy maybe. Odin sours, masking his agitation.  Thor holds up the skull. THOR (CONTâ€™D) You know what this is? ODIN (ADR) The skull of Surtur?  Thatâ€™s a formidable weapon. Thor approaches an E-Guard and hands it over.\'}, {\'name\': \'THOR\', \'text\': \'Do me a favor.  Lock this in a vault so it doesnâ€™t turn into a giant monster and destroy the whole planet. ODIN So itâ€™s back to Midgard for you, is it? Thor starts YO-YOing Mjolnir, turns back to Odin.\'}, {\'name\': \'THOR\', \'text\': \'Nope.  Iâ€™ve been having this reocurring dream lately. (MORE) BLUE DRAFT 05/20/16 12. Every night I see Asgard fall into ruins... ODIN Thatâ€™s just a silly dream... Signs of an overactive imagination.\'}, {\'name\': \'THOR\', \'text\': \'Possibly... but then I decide to go out there and investigate.  And what do I find, but the Nine Realms completely in chaos.  Enemies of Asgard assembling, plotting our demise, all while you, Odin, the protector of those Nine Realms, are sitting here in your bathrobe, eating grapes. ODIN Well, it is best to respect our neighborsâ€™ freedom.\'}, {\'name\': \'THOR\', \'text\': \'Of course, the freedom to be massacred. ODIN Yes, besides, I have been rather busy myself.\'}, {\'name\': \'THOR\', \'text\': \'Watching theatre. ODIN Board meetings, and security council meetings...\'}, {\'name\': \'THOR\', \'text\': \'You really going to make me do it? ODIN Do what? Thor SPINS Mjolnir and then HURLS it off into the distance, GRABS Odin by the back of the neck. Odinâ€™s royal attendants GASP in shock.  The Einherjar bodyguards rush Thor, but he KICKS them away.\'}, {\'name\': \'THOR\', \'text\': "You know that nothing will stop Mjolnir as it returns to my hand. Mjolnir stops mid-air and starts ROCKETING BACK. THOR (CONT\'D) BLUE DRAFT 05/20/16 13. THOR (CONTâ€™D) Not even your face. ODIN Youâ€™ve gone quite mad.  Youâ€™ll be executed for this! Mjolnir approaches at a terrifying speed as Odin struggles."}, {\'name\': \'THOR\', \'text\': \'Then Iâ€™ll see you on the other side...brother. The jig is up.  A shimmering illusion dissipates, revealing:\'}, {\'name\': \'LOKI\', \'text\': \'Alright, I yield! Thor DROPS Loki to the ground and catches Mjolnir.  Loki looks to Thor, hands up defensively.  Skurge arrives on the scene, a little late to warn Loki. SKURGE Behold!  Thor..Odinson.\'}, {\'name\': \'LOKI\', \'text\': \'You had one job!  Just the one.\'}, {\'name\': \'THOR\', \'text\': \'Whereâ€™s Odin?\'}, {\'name\': \'LOKI\', \'text\': \'You just couldnâ€™t stay away, could you?  Everything was fine without you.  Asgard was prospering (gestures to the crowd) Youâ€™ve ruined everything.  Ask them. Those who arenâ€™t freaked out are becoming gradually angrier. Thor advances on Loki, who backs up onto the chaise lounge.\'}, {\'name\': \'THOR\', \'text\': \'Whereâ€™s father?  Did you kill him?\'}, {\'name\': \'LOKI\', \'text\': \'You had what you wanted, you had the independence you asked for! Thor PRESSES Mjolnir onto Lokiâ€™s chest. BLUE DRAFT 05/20/16 14. LOKI (CONTâ€™D) Ow-ow-ow!  Alright!  I know exactly where he is. OMITTED 14 14 OMITTED 15 15 OMITTED 16 16 EXT. SHADY ACRES NURSING HOME - MANHATTAN - DAY 17 17 A NURSING HOME sign on a brick wall. Suddenly the wall crumbles out of shot, revealing a demolition site. Reveal Thor and Loki wearing street clothes.  Thor carries an umbrella, Loki is dressed in a weird avant-garde suit.\'}, {\'name\': \'LOKI\', \'text\': \'I swear, I left him right here.\'}, {\'name\': \'THOR\', \'text\': \'Right here on the sidewalk?  Or right there, where the building thatâ€™s being demolished?  Great planning.\'}, {\'name\': \'LOKI\', \'text\': \'How was I supposed to know? Canâ€™t see into the future.  Iâ€™m not a witch.\'}, {\'name\': \'THOR\', \'text\': \'Then why do you dress like one?\'}, {\'name\': \'LOKI\', \'text\': \'Hey.\'}, {\'name\': \'THOR\', \'text\': \'I canâ€™t believe youâ€™re alive. I saw you die. I mourned you, I cried for you.\'}, {\'name\': \'LOKI\', \'text\': \'Iâ€™m honored. COLLEGE GIRL 2 Ask him. COLLEGE GIRL 1 Hi. Would you mind taking a picture with us? BLUE DRAFT 05/20/16 15.\'}, {\'name\': \'THOR\', \'text\': \'Sure. (to Loki:) Start figuring out where he is. COLLEGE GIRL 1 Oh, my god. COLLEGE GIRL 2 Sorry to hear that Jane dumped you.\'}, {\'name\': \'THOR\', \'text\': \'She didnâ€™t dump me, you know.  I dumped her.  It was a mutual dumping. Thor notices something going on around Loki. THOR (CONTâ€™D) Whatâ€™s this, what are you doing!? Loki looks down to see that the sidewalk has started to GLOW BENEATH HIM!  A circle of ancient symbols.\'}, {\'name\': \'LOKI\', \'text\': \'This... isnâ€™t me. WHOOMPF! Loki DROPS out of sight, vanishing through solid concrete! Thor sees a CARD on the sidewalk where Loki was. Thor pokes the business card.\'}, {\'name\': \'THOR\', \'text\': \'Loki? He picks up the card.  It reads: 177A Bleecker Street Thor picks up the card and - WHOOSH! EXT. SANCTUM SANTORUM - DAY 18 18 Thor approaches 177A Bleecker Street. He knocks ONCE, TWICE, and then WHOOSH! INT. SANCTUM SANCTORUM UPSTAIRS PARLOR - CONTINUOUS 19 19 Thor is suddenly inside Doctor Strangeâ€™s lair! BLUE DRAFT 05/20/16 16. STRANGE (O.S.) Thor Odinson. From a dark corner we glimpse a shape - DOCTOR STRANGE. Levitating, he drifts towards Thor. STRANGE (CONTâ€™D) God of Thunder. Thor holds up the ratty umbrella, ready to defend himself. STRANGE (CONTâ€™D) You can put down the umbrella. Thor gives Strange a sideways look but then sets his umbrella down. When he looks back up, the environment is furnished.\'}, {\'name\': \'THOR\', \'text\': \'So earth has wizards now? STRANGE The pr

In [49]:
import ast

dialouge = {}

for index, row in df.iterrows():

    dialogue_list = ast.literal_eval(row["dialogue"])

    for item in dialogue_list:

        if item["name"] in dialouge:
            dialouge[item["name"]] += item["text"]
        else:
            dialouge[item["name"]] = item["text"] + " "

In [50]:
len(dialouge)

12

In [51]:
new_df = pd.DataFrame()
new_df['character'] = dialouge.keys()
new_df['words'] = dialouge.values()

In [52]:
new_df

        character                                              words
0            FURY  How bad is it? NASA didnâ€™t authorize Selvig ...
1   AGENT COULSON  Thatâ€™s the problem, sir. We donâ€™t know. 5 ...
2      MARIA HILL  It just turned itself on? (CONTINUED) CONTINUE...
3          SELVIG  Director. The Tesseract is misbehaving.No, itâ...
4          BARTON  I see better from a distance. No oneâ€™s come ...
5            LOKI  You have heart. (CONTINUED) CONTINUED: (2) 7. ...
6         NATASHA  (in Russian) I know how you wanted this evenin...
7          BANNER  (in Hindi) Slow down. YOUNG GIRL (in Hindi) My...
8           STEVE  (hitting the bag) Slept for seventy years, Sir...
9            TONY  (into headset) Stark Towerâ€™s about to become...
10         JARVIS  Sir, Agent Coulson of SHIELD is on the line. S...
11           THOR  Where is the Tesseract? Do I look to be in a g...

In [53]:
new_df["word_count"] = new_df["words"].str.split().str.len()

In [54]:
new_df = new_df.sort_values("word_count", ascending=False)

In [55]:
top30 = new_df.head(30)

print(top30[["character", "word_count"]])

        character  word_count
11           THOR       41857
9            TONY       41231
5            LOKI       12489
8           STEVE        8690
3          SELVIG        6638
6         NATASHA        6252
7          BANNER        3934
0            FURY        3381
4          BARTON        1959
1   AGENT COULSON        1415
2      MARIA HILL         938
10         JARVIS         795

In [56]:
top30.head()

   character                                              words  word_count
11      THOR  Where is the Tesseract? Do I look to be in a g...       41857
9       TONY  (into headset) Stark Towerâ€™s about to become...       41231
5       LOKI  You have heart. (CONTINUED) CONTINUED: (2) 7. ...       12489
8      STEVE  (hitting the bag) Slept for seventy years, Sir...        8690
3     SELVIG  Director. The Tesseract is misbehaving.No, itâ...        6638

In [57]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(stop_words='english')

In [58]:
embeddings = cv.fit_transform(top30['words']).toarray()

In [59]:
embeddings.shape

(12, 9961)

In [60]:
embeddings = embeddings.astype('float64')

In [61]:
from sklearn.manifold import TSNE

In [63]:
tsne = TSNE(
    n_components=2,
    perplexity=5,
    verbose=1,
    random_state=123
)

z = tsne.fit_transform(embeddings)

[t-SNE] Computing 11 nearest neighbors...
[t-SNE] Indexed 12 samples in 0.001s...
[t-SNE] Computed neighbors for 12 samples in 2.181s...
[t-SNE] Computed conditional probabilities for sample 12 / 12
[t-SNE] Mean sigma: 74.777915
[t-SNE] KL divergence after 250 iterations with early exaggeration: 55.963657
[t-SNE] KL divergence after 1000 iterations: 0.254726

In [64]:
z.shape

(12, 2)

In [65]:
top30["x"] =z[:, 0]
top30["y"] =z[:, 1]

In [66]:
top30

,character,words,word_count,x,y
11,THOR,Where is the Tesseract? Do I look to be in a g...,41857,18.195728,-13.278081
9,TONY,(into headset) Stark Towerâ€™s about to become...,41231,-15.400810,-20.787737
5,LOKI,You have heart. (CONTINUED) CONTINUED: (2) 7. ...,12489,-17.414171,7.172830
8,STEVE,"(hitting the bag) Slept for seventy years, Sir...",8690,-4.850488,-11.809994
3,SELVIG,"Director. The Tesseract is misbehaving.No, itâ...",6638,25.046864,13.716648
6,NATASHA,(in Russian) I know how you wanted this evenin...,6252,0.395468,2.536785
7,BANNER,(in Hindi) Slow down. YOUNG GIRL (in Hindi) My...,3934,-6.166217,21.388577
0,FURY,How bad is it? NASA didnâ€™t authorize Selvig ...,3381,14.488001,42.512352
4,BARTON,I see better from a distance. No oneâ€™s come ...,1959,9.472191,19.607441
1,AGENT COULSON,"Thatâ€™s the problem, sir. We donâ€™t know. 5 ...",1415,18.020016,29.737747
2,MARIA HILL,It just turned itself on? (CONTINUED) CONTINUE...,938,0.015412,40.011375
10,JARVIS,"Sir, Agent Coulson of SHIELD is on the line. S...",795,5.817044,30.831596

In [67]:
import plotly.express as px
fig = px.scatter(top30.head(25), x="x", y="y", color="character")
fig.show()

In [68]:
from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity(embeddings)

print(similarity.shape)

(12, 12)

In [69]:
similarity

array([[1.        , 0.30790324, 0.83329491, 0.46627096, 0.58942552,
        0.47122112, 0.58602248, 0.35722426, 0.42127069, 0.30465767,
        0.2977597 , 0.27329538],
       [0.30790324, 1.        , 0.28689146, 0.51383701, 0.20228506,
        0.49187213, 0.38238096, 0.39527398, 0.35421074, 0.38540037,
        0.28213248, 0.37825397],
       [0.83329491, 0.28689146, 1.        , 0.35859863, 0.51911698,
        0.41731009, 0.49193518, 0.43502999, 0.46499281, 0.32232879,
        0.28488065, 0.27597537],
       [0.46627096, 0.51383701, 0.35859863, 1.        , 0.24775075,
        0.71445891, 0.45055091, 0.39194911, 0.34169666, 0.3294945 ,
        0.27778381, 0.26012063],
       [0.58942552, 0.20228506, 0.51911698, 0.24775075, 1.        ,
        0.25547523, 0.27476375, 0.25442481, 0.26485539, 0.26147189,
        0.1946356 , 0.19810687],
       [0.47122112, 0.49187213, 0.41731009, 0.71445891, 0.25547523,
        1.        , 0.5367983 , 0.49252716, 0.53851915, 0.43480512,
        0.35691539, 0.3426779 ],
       [0.58602248, 0.38238096, 0.49193518, 0.45055091, 0.27476375,
        0.5367983 , 1.        , 0.50794576, 0.46142302, 0.43441462,
        0.39941957, 0.31838353],
       [0.35722426, 0.39527398, 0.43502999, 0.39194911, 0.25442481,
        0.49252716, 0.50794576, 1.        , 0.58253868, 0.62936539,
        0.58454598, 0.39327505],
       [0.42127069, 0.35421074, 0.46499281, 0.34169666, 0.26485539,
        0.53851915, 0.46142302, 0.58253868, 1.        , 0.46496724,
        0.49720506, 0.49132274],
       [0.30465767, 0.38540037, 0.32232879, 0.3294945 , 0.26147189,
        0.43480512, 0.43441462, 0.62936539, 0.46496724, 1.        ,
        0.45849249, 0.33778042],
       [0.2977597 , 0.28213248, 0.28488065, 0.27778381, 0.1946356 ,
        0.35691539, 0.39941957, 0.58454598, 0.49720506, 0.45849249,
        1.        , 0.47492584],
       [0.27329538, 0.37825397, 0.27597537, 0.26012063, 0.19810687,
        0.3426779 , 0.31838353, 0.39327505, 0.49132274, 0.33778042,
        0.47492584, 1.        ]])

In [70]:
print(top30["character"].values)

<StringArray>
[         'THOR',          'TONY',          'LOKI',         'STEVE',
        'SELVIG',       'NATASHA',        'BANNER',          'FURY',
        'BARTON', 'AGENT COULSON',    'MARIA HILL',        'JARVIS']
Length: 12, dtype: str

In [71]:
character = "TONY"

index = new_df.index[new_df["character"] == character][0]

scores = similarity[index]

print(scores)

[0.30465767 0.38540037 0.32232879 0.3294945  0.26147189 0.43480512
 0.43441462 0.62936539 0.46496724 1.         0.45849249 0.33778042]

In [72]:
similar_indices = scores.argsort()[::-1]

print(similar_indices)

[ 9  7  8 10  5  6  1 11  3  2  0  4]

In [73]:
top_indices = similar_indices[1:6]

for i in top_indices:
    print(new_df.iloc[i]["character"], scores[i])

FURY 0.6293653886296156
BARTON 0.4649672378982549
MARIA HILL 0.4584924875311344
NATASHA 0.4348051210052964
BANNER 0.4344146165874033

In [74]:
def find_similar(character, similarity, df, n=5):

    index = df.index[df["character"] == character][0]

    scores = similarity[index]

    similar_indices = scores.argsort()[::-1]

    top_indices = similar_indices[1:n+1]

    for i in top_indices:
        print(df.iloc[i]["character"], scores[i])

In [75]:
find_similar("TONY", similarity, new_df)

FURY 0.6293653886296156
BARTON 0.4649672378982549
MARIA HILL 0.4584924875311344
NATASHA 0.4348051210052964
BANNER 0.4344146165874033

In [76]:
find_similar("STEVE", similarity, new_df)

FURY 0.5825386758959901
NATASHA 0.5385191465925172
MARIA HILL 0.497205062228617
JARVIS 0.4913227354580314
LOKI 0.46499280778486995

In [79]:
def find_similar(character, similarity, df, n=5):

    index = df.index[df["character"] == character][0]

    scores = similarity[index]

    similar_indices = scores.argsort()[::-1]

    top_indices = similar_indices[1:n+1]

    results = []

    for i in top_indices:
        results.append({
    "character": df.iloc[i]["character"],
    "score": round(scores[i] * 100, 2)
})

    return results

In [80]:
results = find_similar("TONY", similarity, new_df)

print(results)

[{'character': 'FURY', 'score': np.float64(62.94)}, {'character': 'BARTON', 'score': np.float64(46.5)}, {'character': 'MARIA HILL', 'score': np.float64(45.85)}, {'character': 'NATASHA', 'score': np.float64(43.48)}, {'character': 'BANNER', 'score': np.float64(43.44)}]

In [81]:
characters = new_df["character"].tolist()

print(characters)

['THOR', 'TONY', 'LOKI', 'STEVE', 'SELVIG', 'NATASHA', 'BANNER', 'FURY', 'BARTON', 'AGENT COULSON', 'MARIA HILL', 'JARVIS']

In [82]:
pip install streamlit

Collecting streamlit
  Downloading streamlit-1.61.1-py3-none-any.whl.metadata (10 kB)
Collecting altair!=5.4.0,!=5.4.1,<7,>=5.0.0 (from streamlit)
  Downloading altair-6.2.2-py3-none-any.whl.metadata (11 kB)
Collecting blinker<2,>=1.5.0 (from streamlit)
  Downloading blinker-1.9.0-py3-none-any.whl.metadata (1.6 kB)
Collecting click<9,>=7.0 (from streamlit)
  Downloading click-8.4.2-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: numpy<3,>=1.23 in C:\Users\banda\PycharmProjects\PythonProject\.venv\Lib\site-packages (from streamlit) (2.4.6)
Requirement already satisfied: packaging>=20 in C:\Users\banda\PycharmProjects\PythonProject\.venv\Lib\site-packages (from streamlit) (26.2)
Requirement already satisfied: pandas<4,>=1.4.0 in C:\Users\banda\PycharmProjects\PythonProject\.venv\Lib\site-packages (from streamlit) (3.0.3)
Requirement already satisfied: pillow<13,>=7.1.0 in C:\Users\banda\PycharmProjects\PythonProject\.venv\Lib\site-packages (from streamlit) (12.2.0)
Collecting pydeck<1,>=0.8.0b4 (from streamlit)
  Downloading pydeck-0.9.3-py2.py3-none-any.whl.metadata (4.2 kB)
Collecting protobuf<8,>=5.26.1 (from streamlit)
  Downloading protobuf-7.35.1-cp310-abi3-win_amd64.whl.metadata (595 bytes)
Collecting pyarrow<25,>=7.0 (from streamlit)
  Downloading pyarrow-24.0.0-cp314-cp314-win_amd64.whl.metadata (3.0 kB)
Requirement already satisfied: requests<3,>=2.27 in C:\Users\banda\PycharmProjects\PythonProject\.venv\Lib\site-packages (from streamlit) (2.34.2)
Collecting tenacity<10,>=8.1.0 (from streamlit)
  Downloading tenacity-9.1.4-py3-none-any.whl.metadata (1.2 kB)
Collecting toml<2,>=0.10.1 (from streamlit)
  Downloading toml-0.10.2-py2.py3-none-any.whl.metadata (7.1 kB)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in C:\Users\banda\PycharmProjects\PythonProject\.venv\Lib\site-packages (from streamlit) (4.15.0)
Collecting starlette<1.4.0,>=0.46.0 (from streamlit)
  Downloading starlette-1.3.1-py3-none-any.whl.metadata (6.4 kB)
Collecting uvicorn<1,>=0.30.0 (from streamlit)
  Downloading uvicorn-0.52.1-py3-none-any.whl.metadata (6.6 kB)
Collecting httptools<1,>=0.6.3 (from streamlit)
  Downloading httptools-0.8.0-cp314-cp314-win_amd64.whl.metadata (3.7 kB)
Collecting anyio<5,>=4.0.0 (from streamlit)
  Downloading anyio-4.14.2-py3-none-any.whl.metadata (4.6 kB)
Collecting python-multipart<1,>=0.0.10 (from streamlit)
  Downloading python_multipart-0.0.32-py3-none-any.whl.metadata (2.1 kB)
Collecting websockets<17,>=12.0.0 (from streamlit)
  Downloading websockets-16.1.1-cp314-cp314-win_amd64.whl.metadata (7.0 kB)
Collecting itsdangerous<3,>=2.1.2 (from streamlit)
  Downloading itsdangerous-2.2.0-py3-none-any.whl.metadata (1.9 kB)
Collecting watchdog<7,>=2.1.5 (from streamlit)
  Downloading watchdog-6.0.0-py3-none-win_amd64.whl.metadata (44 kB)
Collecting jinja2 (from altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit)
  Using cached jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
Requirement already satisfied: jsonschema>=3.0 in C:\Users\banda\PycharmProjects\PythonProject\.venv\Lib\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (4.26.0)
Requirement already satisfied: narwhals>=2.4.0 in C:\Users\banda\PycharmProjects\PythonProject\.venv\Lib\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (2.22.1)
Requirement already satisfied: idna>=2.8 in C:\Users\banda\PycharmProjects\PythonProject\.venv\Lib\site-packages (from anyio<5,>=4.0.0->streamlit) (3.18)
Requirement already satisfied: colorama in C:\Users\banda\PycharmProjects\PythonProject\.venv\Lib\site-packages (from click<9,>=7.0->streamlit) (0.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\banda\PycharmProjects\PythonProject\.venv\Lib\site-packages (from pandas<4,>=1.4.0->streamlit) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\banda\PycharmProjects\PythonProject\.venv\Lib\site-packages (from pandas<4,>=1.4.0->streamlit) (2026.2)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\banda\PycharmProjects\PythonProject\.venv\Lib\site-packages (from requests<3,>=2.27->streamlit) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Users\banda\PycharmProjects\PythonProject\.venv\Lib\site-packages (from requests<3,>=2.27->streamlit) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in C:\Users\banda\PycharmProjects\PythonProject\.venv\Lib\site-packages (from requests<3,>=2.27->streamlit) (2026.6.17)
Collecting h11>=0.8 (from uvicorn<1,>=0.30.0->streamlit)
  Downloading h11-0.16.0-py3-none-any.whl.metadata (8.3 kB)
Collecting MarkupSafe>=2.0 (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit)
  Downloading markupsafe-3.0.3-cp314-cp314-win_amd64.whl.metadata (2.8 kB)
Requirement already satisfied: attrs>=22.2.0 in C:\Users\banda\PycharmProjects\PythonProject\.venv\Lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in C:\Users\banda\PycharmProjects\PythonProject\.venv\Lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in C:\Users\banda\PycharmProjects\PythonProject\.venv\Lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in C:\Users\banda\PycharmProjects\PythonProject\.venv\Lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=5.0.0->streamlit) (2026.6.3)
Requirement already satisfied: six>=1.5 in C:\Users\banda\PycharmProjects\PythonProject\.venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas<4,>=1.4.0->streamlit) (1.17.0)
Downloading streamlit-1.61.1-py3-none-any.whl (10.5 MB)
   ---------------------------------------- 0.0/10.5 MB ? eta -:--:--
   --------- ------------------------------ 2.6/10.5 MB 16.2 MB/s eta 0:00:01
   ---------------------- ----------------- 6.0/10.5 MB 15.7 MB/s eta 0:00:01
   ------------------------------------ --- 9.7/10.5 MB 16.6 MB/s eta 0:00:01
   ---------------------------------------- 10.5/10.5 MB 14.6 MB/s  0:00:00
Downloading altair-6.2.2-py3-none-any.whl (797 kB)
   ---------------------------------------- 0.0/797.6 kB ? eta -:--:--
   ---------------------------------------- 797.6/797.6 kB 11.2 MB/s  0:00:00
Downloading anyio-4.14.2-py3-none-any.whl (125 kB)
Downloading blinker-1.9.0-py3-none-any.whl (8.5 kB)
Downloading click-8.4.2-py3-none-any.whl (119 kB)
Downloading httptools-0.8.0-cp314-cp314-win_amd64.whl (92 kB)
Downloading itsdangerous-2.2.0-py3-none-any.whl (16 kB)
Downloading protobuf-7.35.1-cp310-abi3-win_amd64.whl (439 kB)
Downloading pyarrow-24.0.0-cp314-cp314-win_amd64.whl (28.0 MB)
   ---------------------------------------- 0.0/28.0 MB ? eta -:--:--
   --- ------------------------------------ 2.6/28.0 MB 8.3 MB/s eta 0:00:04
   --------- ------------------------------ 6.8/28.0 MB 11.4 MB/s eta 0:00:02
   ------------- -------------------------- 9.4/28.0 MB 11.6 MB/s eta 0:00:02
   ----------------- ---------------------- 12.1/28.0 MB 11.7 MB/s eta 0:00:02
   --------------------- ------------------ 14.9/28.0 MB 12.0 MB/s eta 0:00:02
   ------------------------ --------------- 17.0/28.0 MB 11.8 MB/s eta 0:00:01
   ---------------------------- ----------- 19.7/28.0 MB 11.8 MB/s eta 0:00:01
   -------------------------------- ------- 22.8/28.0 MB 12.1 MB/s eta 0:00:01
   ------------------------------------- -- 26.0/28.0 MB 12.4 MB/s eta 0:00:01
   ---------------------------------------- 28.0/28.0 MB 12.2 MB/s  0:00:02
Downloading pydeck-0.9.3-py2.py3-none-any.whl (11.4 MB)
   ---------------------------------------- 0.0/11.4 MB ? eta -:--:--
   ----------- ---------------------------- 3.1/11.4 MB 15.4 MB/s eta 0:00:01
   ---------------------- ----------------- 6.6/11.4 MB 15.7 MB/s eta 0:00:01
   ----------------------------------- ---- 10.2/11.4 MB 16.3 MB/s eta 0:00:01
   ---------------------------------------- 11.4/11.4 MB 15.2 MB/s  0:00:00
Downloading python_multipart-0.0.32-py3-none-any.whl (30 kB)
Downloading starlette-1.3.1-py3-none-any.whl (73 kB)
Downloading tenacity-9.1.4-py3-none-any.whl (28 kB)
Downloading toml-0.10.2-py2.py3-none-any.whl (16 kB)
Downloading uvicorn-0.52.1-py3-none-any.whl (79 kB)
Downloading watchdog-6.0.0-py3-none-win_amd64.whl (79 kB)
Downloading websockets-16.1.1-cp314-cp314-win_amd64.whl (179 kB)
Downloading h11-0.16.0-py3-none-any.whl (37 kB)
Downloading jinja2-3.1.6-py3-none-any.whl (134 kB)
Downloading markupsafe-3.0.3-cp314-cp314-win_amd64.whl (15 kB)
Installing collected packages: websockets, watchdog, toml, tenacity, python-multipart, pyarrow, protobuf, MarkupSafe, itsdangerous, httptools, h11, click, blinker, anyio, uvicorn, starlette, jinja2, pydeck, altair, streamlit

   ----------------------------------------  0/20 [websockets]
   -- -------------------------------------  1/20 [watchdog]
   ------ ---------------------------------  3/20 [tenacity]
   ---------- -----------------------------  5/20 [pyarrow]
   ---------- -----------------------------  5/20 [pyarrow]
   ---------- -----------------------------  5/20 [pyarrow]
   ---------- -----------------------------  5/20 [pyarrow]
   ---------- -----------------------------  5/20 [pyarrow]
   ---------- -----------------------------  5/20 [pyarrow]
   ---------- -----------------------------  5/20 [pyarrow]
   ---------- -----------------------------  5/20 [pyarrow]
   ---------- -----------------------------  5/20 [pyarrow]
   ---------- -----------------------------  5/20 [pyarrow]
   ------------ ---------------------------  6/20 [protobuf]
   ---------------- -----------------------  8/20 [itsdangerous]
   ---------------------- ----------------- 11/20 [click]
   -------------------------- ------------- 13/20 [anyio]
   -------------------------- ------------- 13/20 [anyio]
   ---------------------------- ----------- 14/20 [uvicorn]
   ------------------------------ --------- 15/20 [starlette]
   -------------------------------- ------- 16/20 [jinja2]
   -------------------------------- ------- 16/20 [jinja2]
   ---------------------------------- ----- 17/20 [pydeck]
   ---------------------------------- ----- 17/20 [pydeck]
   ------------------------------------ --- 18/20 [altair]
   ------------------------------------ --- 18/20 [altair]
   ------------------------------------ --- 18/20 [altair]
   -------------------------------------- - 19/20 [streamlit]
   -------------------------------------- - 19/20 [streamlit]
   -------------------------------------- - 19/20 [streamlit]
   -------------------------------------- - 19/20 [streamlit]
   -------------------------------------- - 19/20 [streamlit]
   -------------------------------------- - 19/20 [streamlit]
   -------------------------------------- - 19/20 [streamlit]
   -------------------------------------- - 19/20 [streamlit]
   -------------------------------------- - 19/20 [streamlit]
   -------------------------------------- - 19/20 [streamlit]
   -------------------------------------- - 19/20 [streamlit]
   -------------------------------------- - 19/20 [streamlit]
   -------------------------------------- - 19/20 [streamlit]
   ---------------------------------------- 20/20 [streamlit]

Successfully installed MarkupSafe-3.0.3 altair-6.2.2 anyio-4.14.2 blinker-1.9.0 click-8.4.2 h11-0.16.0 httptools-0.8.0 itsdangerous-2.2.0 jinja2-3.1.6 protobuf-7.35.1 pyarrow-24.0.0 pydeck-0.9.3 python-multipart-0.0.32 starlette-1.3.1 streamlit-1.61.1 tenacity-9.1.4 toml-0.10.2 uvicorn-0.52.1 watchdog-6.0.0 websockets-16.1.1
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [83]:
similarity = cosine_similarity(embeddings)

In [85]:
new_df.to_csv("characters.csv", index=False)

In [86]:
import numpy as np

np.save("similarity.npy", similarity)